; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
[ DataSettings ]
datatype=Newick Tree
[ ProcessTypes ]
ppRelTimeBLens=true
[ AnalysisSettings ]
