; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                       = 12210916-x86_64-DEVELOPER MS Windows     
[ DataSettings ]
datatype                                  = snNucleotide                             
containsCodingNuc                         = True                                     
MissingBaseSymbol                         = ?                                        
IdenticalBaseSymbol                       = .                                        
GapSymbol                                 = -                                        
Labelled Sites                            = All Sites                                
Labels to Include                         =                                          
[ ProcessTypes ]
ppInfer                                   = true                                     
ppML                                      = true                                     
[ AnalysisSettings ]
Analysis                                  = Phylogeny Reconstruction                 
Statistical Method                        = Maximum Likelihood                       
Phylogeny Test                            = ====================                     
Test of Phylogeny                         = Little Bootstraps method                 
No. of Bootstrap Replications             = Not Applicable                           
Parameter Optimizations                   = Automatic                                
Max No. of Bootstrap Sub-samples          = Not Applicable                           
Max No. of Replicates per Sub-sample      = Not Applicable                           
Starting No. of Sites per Sub-sample      = Not Applicable                           
Max No. of Sites per Sub-sample           = Not Applicable                           
Sample Size Factor                        = Not Applicable                           
Threshold for No. of Reps                 = Not Applicable                           
Threshold for No. of Samples              = Not Applicable                           
Target Stable BCL Threshold               = Not Applicable                           
Substitution Model                        = ====================                     
Substitutions Type                        = Nucleotide                               
Model/Method                              = Hasegawa-Kishino-Yano model            
Rates and Patterns                        = ====================                     
Rates among Sites                         = Gamma Distributed (G)                    
No of Discrete Gamma Categories           = 5                                        
Data Subset to Use                        = ====================                     
Gaps/Missing Data Treatment               = Use all sites                            
Site Coverage Cutoff (%)                  = Not Applicable                           
Select Codon Positions                    = 1st, 2nd, 3rd, Non-Coding                
Tree Inference Options                    = ====================                     
ML Heuristic Method                       = Nearest-Neighbor-Interchange (NNI)       
Initial Tree for ML                       = Make initial tree automatically (Default - NJ/BioNJ) 
Branch Swap Filter                        = None                                     
System Resource Usage                     = ====================                     
Number of Threads                         = 3                                        
Genetic Code Table                        = Not Applicable                           
Genetic Code                              = Not Applicable                           
Has Time Limit                            = False                                    
Maximum Execution Time                    = -1                                       
